import esbuild from 'esbuild';
import { copyFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const builtins = [
    'assert', 'buffer', 'child_process', 'cluster', 'console', 'constants',
    'crypto', 'dgram', 'dns', 'domain', 'events', 'fs', 'http', 'https',
    'module', 'net', 'os', 'path', 'process', 'punycode', 'querystring',
    'readline', 'repl', 'stream', 'string_decacer', 'sys', 'timers', 'tls',
    'tty', 'url', 'util', 'v8', 'vm', 'zlib',
];

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const isProduction = process.argv.includes('production');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: [join(__dirname, 'src', 'main.ts')],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2020',
    logLevel: 'info',
    sourcemap: isProduction ? false : 'inline',
    treeShaking: true,
    outfile: join(__dirname, 'main.js'),
});

if (isProduction) {
    await context.rebuild();
    await context.dispose();
} else {
    await context.watch();
    // 复制 manifest.json 和 styles.css 到构建输出（dev 模式一次性操作）
    const copyAssets = () => {
        const destDir = __dirname;
        ['manifest.json', 'styles.css'].forEach((file) => {
            const src = join(__dirname, file);
            if (existsSync(src)) {
                copyFileSync(src, join(destDir, file));
            }
        });
    };
    copyAssets();
}
