/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NotePipePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/i18n/locales/en.ts
var en_default = {
  // Commands
  "command.copyWithContext": "Copy with context",
  "command.copyWithContextGlobal": "Copy with context (global)",
  // Notices
  "notice.noContext": "No context available",
  "notice.noActiveFile": "No active file",
  "notice.noTextSelected": "No text selected",
  "notice.copied": "Copied with context",
  "notice.clipboardUnavailable": "Clipboard unavailable",
  "notice.truncated": "... (truncated)",
  // Floating button
  "floating.label": "Copy context",
  "floating.tooltip": "Copy with file path and line number",
  // Settings
  "settings.templates": "Templates",
  "settings.templatesDesc": "Use variables to customize the output format.",
  "settings.singleLine": "Single-line template",
  "settings.singleLineDesc": "Used when selection spans a single line.",
  "settings.multiLine": "Multi-line template",
  "settings.multiLineDesc": "Used when selection spans multiple lines.",
  "settings.variableReference": "Available variables",
  "settings.path": "Path",
  "settings.pathStyle": "Path format",
  "settings.pathStyleDesc": "Absolute: full path, ready for terminal use. Vault-relative: portable across machines.",
  "settings.pathAbsolute": "Absolute",
  "settings.pathVaultRelative": "Vault-relative",
  "settings.triggers": "Triggers",
  "settings.showFloatingButton": "Show floating button",
  "settings.showFloatingButtonDesc": "Show a floating copy button when text is selected.",
  "settings.enableHotkey": "Enable hotkey",
  "settings.enableHotkeyDesc": "Enable Ctrl+Shift+C / Cmd+Shift+C shortcut.",
  "settings.advanced": "Advanced",
  "settings.alwaysCopy": "Always copy mode (experimental)",
  "settings.alwaysCopyDesc": "Automatically copy with context on every text selection. May cause performance issues.",
  "settings.alwaysCopyWarning": "\u26A0\uFE0F Experimental: may conflict with clipboard managers."
};

// src/i18n/locales/zh.ts
var zh_default = {
  // 命令
  "command.copyWithContext": "\u590D\u5236\u5E76\u9644\u5E26\u4E0A\u4E0B\u6587",
  "command.copyWithContextGlobal": "\u590D\u5236\u5E76\u9644\u5E26\u4E0A\u4E0B\u6587\uFF08\u5168\u5C40\uFF09",
  // 通知
  "notice.noContext": "\u65E0\u53EF\u7528\u4E0A\u4E0B\u6587",
  "notice.noActiveFile": "\u65E0\u6D3B\u52A8\u6587\u4EF6",
  "notice.noTextSelected": "\u672A\u9009\u4E2D\u6587\u672C",
  "notice.copied": "\u5DF2\u590D\u5236\uFF08\u9644\u5E26\u4E0A\u4E0B\u6587\uFF09",
  "notice.clipboardUnavailable": "\u526A\u8D34\u677F\u4E0D\u53EF\u7528",
  "notice.truncated": "...\uFF08\u5DF2\u622A\u65AD\uFF09",
  // 浮层按钮
  "floating.label": "\u590D\u5236\u4E0A\u4E0B\u6587",
  "floating.tooltip": "\u590D\u5236\u6587\u4EF6\u8DEF\u5F84\u548C\u884C\u53F7",
  // 设置
  "settings.templates": "\u6A21\u677F",
  "settings.templatesDesc": "\u4F7F\u7528\u53D8\u91CF\u81EA\u5B9A\u4E49\u8F93\u51FA\u683C\u5F0F\u3002",
  "settings.singleLine": "\u5355\u884C\u6A21\u677F",
  "settings.singleLineDesc": "\u9009\u4E2D\u5355\u884C\u6587\u672C\u65F6\u4F7F\u7528\u3002",
  "settings.multiLine": "\u591A\u884C\u6A21\u677F",
  "settings.multiLineDesc": "\u9009\u4E2D\u591A\u884C\u6587\u672C\u65F6\u4F7F\u7528\u3002",
  "settings.variableReference": "\u53EF\u7528\u53D8\u91CF",
  "settings.path": "\u8DEF\u5F84",
  "settings.pathStyle": "\u8DEF\u5F84\u683C\u5F0F",
  "settings.pathStyleDesc": "\u7EDD\u5BF9\u8DEF\u5F84\uFF1A\u5B8C\u6574\u8DEF\u5F84\uFF0C\u53EF\u76F4\u63A5\u5728\u7EC8\u7AEF\u5B9A\u4F4D\u3002\u5E93\u76F8\u5BF9\u8DEF\u5F84\uFF1A\u8DE8\u673A\u5668\u53EF\u79FB\u690D\u3002",
  "settings.pathAbsolute": "\u7EDD\u5BF9\u8DEF\u5F84",
  "settings.pathVaultRelative": "\u5E93\u76F8\u5BF9\u8DEF\u5F84",
  "settings.triggers": "\u89E6\u53D1\u65B9\u5F0F",
  "settings.showFloatingButton": "\u663E\u793A\u6D6E\u5C42\u6309\u94AE",
  "settings.showFloatingButtonDesc": "\u9009\u4E2D\u6587\u672C\u65F6\u663E\u793A\u6D6E\u5C42\u590D\u5236\u6309\u94AE\u3002",
  "settings.enableHotkey": "\u542F\u7528\u5FEB\u6377\u952E",
  "settings.enableHotkeyDesc": "\u542F\u7528 Ctrl+Shift+C / Cmd+Shift+C \u5FEB\u6377\u952E\u3002",
  "settings.advanced": "\u9AD8\u7EA7",
  "settings.alwaysCopy": "\u59CB\u7EC8\u590D\u5236\u6A21\u5F0F\uFF08\u5B9E\u9A8C\u6027\uFF09",
  "settings.alwaysCopyDesc": "\u6BCF\u6B21\u9009\u4E2D\u6587\u672C\u65F6\u81EA\u52A8\u9644\u5E26\u4E0A\u4E0B\u6587\u590D\u5236\u3002\u53EF\u80FD\u5BFC\u81F4\u6027\u80FD\u95EE\u9898\u3002",
  "settings.alwaysCopyWarning": "\u26A0\uFE0F \u5B9E\u9A8C\u6027\u529F\u80FD\uFF1A\u53EF\u80FD\u4E0E\u526A\u8D34\u677F\u7BA1\u7406\u5668\u51B2\u7A81\u3002"
};

// src/i18n/index.ts
var locales = { en: en_default, zh: zh_default };
var currentLang = "en";
function loadLocale() {
  try {
    const lang = (typeof localStorage !== "undefined" ? localStorage.getItem("language") : null) || "en";
    currentLang = lang.startsWith("zh") ? "zh" : "en";
  } catch {
    currentLang = "en";
  }
}
function t(key, ...args) {
  const template = locales[currentLang]?.[key] ?? locales["en"][key] ?? key;
  return args.reduce((s, arg, i) => s.replace(`{${i}}`, arg), template);
}

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  singleLineTemplate: "{{path}}:{{startLine}}\n{{selection}}",
  multiLineTemplate: "{{path}}:{{startLine}}-{{endLine}}\n{{selection}}",
  pathStyle: "absolute",
  showFloatingButton: true,
  enableHotkey: true,
  enableAlwaysCopy: false
};
var NotePipeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: t("settings.templates") });
    containerEl.createEl("p", {
      text: t("settings.templatesDesc"),
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName(t("settings.singleLine")).setDesc(t("settings.singleLineDesc")).addTextArea((textarea) => {
      textarea.setValue(this.plugin.settings.singleLineTemplate).onChange(async (value) => {
        this.plugin.settings.singleLineTemplate = value;
        await this.plugin.saveSettings();
      });
      textarea.inputEl.rows = 2;
      textarea.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName(t("settings.multiLine")).setDesc(t("settings.multiLineDesc")).addTextArea((textarea) => {
      textarea.setValue(this.plugin.settings.multiLineTemplate).onChange(async (value) => {
        this.plugin.settings.multiLineTemplate = value;
        await this.plugin.saveSettings();
      });
      textarea.inputEl.rows = 2;
      textarea.inputEl.style.width = "100%";
    });
    const varRef = containerEl.createDiv({ cls: "setting-item-description" });
    varRef.createEl("strong", { text: t("settings.variableReference") });
    const vars = [
      "{{path}}",
      "{{fileName}}",
      "{{startLine}}",
      "{{endLine}}",
      "{{selection}}",
      "{{lines}}",
      "{{folder}}"
    ];
    varRef.createEl("br");
    varRef.createEl("code", { text: vars.join("  ") });
    containerEl.createEl("h3", { text: t("settings.path") });
    new import_obsidian.Setting(containerEl).setName(t("settings.pathStyle")).setDesc(t("settings.pathStyleDesc")).addDropdown((dropdown) => {
      dropdown.addOption("absolute", t("settings.pathAbsolute")).addOption("vault-relative", t("settings.pathVaultRelative")).setValue(this.plugin.settings.pathStyle).onChange(async (value) => {
        this.plugin.settings.pathStyle = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: t("settings.triggers") });
    new import_obsidian.Setting(containerEl).setName(t("settings.showFloatingButton")).setDesc(t("settings.showFloatingButtonDesc")).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showFloatingButton).onChange(async (value) => {
        this.plugin.settings.showFloatingButton = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(t("settings.enableHotkey")).setDesc(t("settings.enableHotkeyDesc")).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableHotkey).onChange(async (value) => {
        this.plugin.settings.enableHotkey = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: t("settings.advanced") });
    const alwaysCopyWarning = containerEl.createDiv({
      cls: "setting-item-description"
    });
    alwaysCopyWarning.createEl("strong", {
      text: t("settings.alwaysCopyWarning")
    });
    new import_obsidian.Setting(containerEl).setName(t("settings.alwaysCopy")).setDesc(t("settings.alwaysCopyDesc")).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.enableAlwaysCopy).onChange(async (value) => {
        this.plugin.settings.enableAlwaysCopy = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/context-resolver.ts
var import_obsidian2 = require("obsidian");
function formatPath(vaultRelativePath, pathStyle, app) {
  if (pathStyle === "absolute") {
    const adapter = app.vault.adapter;
    if (adapter instanceof import_obsidian2.FileSystemAdapter) {
      const basePath = adapter.getBasePath();
      return basePath.replace(/\\/g, "/") + "/" + vaultRelativePath;
    }
    return vaultRelativePath;
  }
  return vaultRelativePath;
}
function resolveEditorContext(editor, file) {
  const selection = editor.getSelection();
  const from = editor.getCursor("from");
  const to = editor.getCursor("to");
  const isEmpty = selection.trim().length === 0;
  return {
    source: "editor-edit",
    path: file.path,
    selection: selection || null,
    startLine: isEmpty ? null : from.line + 1,
    endLine: isEmpty ? null : to.line + 1
  };
}
async function resolvePreviewContext(app, file) {
  const domSelection = window.getSelection()?.toString();
  if (!domSelection) return null;
  const content = await app.vault.cachedRead(file);
  const index = content.indexOf(domSelection);
  let startLine = null;
  let endLine = null;
  if (index !== -1) {
    const before = content.substring(0, index);
    startLine = before.split("\n").length;
    endLine = startLine + domSelection.split("\n").length - 1;
  }
  return {
    source: "editor-preview",
    path: file.path,
    selection: domSelection,
    startLine,
    endLine
  };
}
function resolveFileExplorerContext() {
  const selectedItems = document.querySelectorAll(
    ".nav-file.is-selected, .nav-folder.is-selected"
  );
  if (selectedItems.length === 0) return null;
  const files = [];
  selectedItems.forEach((item) => {
    const titleEl = item.querySelector(
      ".nav-file-title-content, .nav-folder-title-content"
    );
    if (titleEl) {
      const path = titleEl.getAttribute("data-path") || titleEl.textContent || "";
      if (path) files.push(path);
    }
  });
  return {
    source: "file-explorer",
    path: "",
    selection: null,
    startLine: null,
    endLine: null,
    files
  };
}
async function resolveContext(app, editor, view) {
  if (editor && view && view.file) {
    const sel = editor.getSelection();
    if (sel.trim().length > 0) {
      return resolveEditorContext(editor, view.file);
    }
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    return {
      source: "editor-edit",
      path: view.file.path,
      selection: line,
      startLine: cursor.line + 1,
      endLine: cursor.line + 1
    };
  }
  const activeView = app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
  if (activeView && activeView.getMode() === "preview" && activeView.file) {
    const domSelection = window.getSelection()?.toString();
    if (domSelection && domSelection.trim().length > 0) {
      return resolvePreviewContext(app, activeView.file);
    }
  }
  const fileExplorerContext = resolveFileExplorerContext();
  if (fileExplorerContext) return fileExplorerContext;
  const activeFile = app.workspace.getActiveFile();
  if (activeFile) {
    return {
      source: "unknown",
      path: activeFile.path,
      selection: null,
      startLine: null,
      endLine: null
    };
  }
  return null;
}

// src/template-engine.ts
function buildTemplateContext(path, selection, startLine, endLine) {
  const parts = path.split("/");
  const fileNameWithExt = parts[parts.length - 1] ?? "";
  const fileName = fileNameWithExt.replace(/\.[^.]+$/, "");
  const folder = parts.length > 1 ? parts.slice(0, -1).join("/") : "";
  let lines;
  if (startLine === null) {
    lines = "";
  } else if (endLine === null || endLine === startLine) {
    lines = `Line ${startLine}`;
  } else {
    lines = `Lines ${startLine}-${endLine}`;
  }
  return { path, fileName, startLine, endLine, selection, lines, folder };
}
function renderTemplate(template, context) {
  return template.replace(/\{\{path\}\}/g, context.path).replace(/\{\{fileName\}\}/g, context.fileName).replace(/\{\{startLine\}\}/g, context.startLine?.toString() ?? "").replace(/\{\{endLine\}\}/g, context.endLine?.toString() ?? "").replace(/\{\{selection\}\}/g, context.selection ?? "").replace(/\{\{lines\}\}/g, context.lines).replace(/\{\{folder\}\}/g, context.folder).replace(/\\n/g, "\n");
}
function truncateSelection(selection, maxBytes = 100 * 1024, truncationHint = "... (truncated)") {
  if (selection.length < maxBytes) return selection;
  let bytes = 0;
  let charCount = 0;
  for (const char of selection) {
    const charBytes = new TextEncoder().encode(char).length;
    if (bytes + charBytes > maxBytes) break;
    bytes += charBytes;
    charCount++;
  }
  return selection.slice(0, charCount) + truncationHint;
}

// src/floating-button.ts
var import_view = require("@codemirror/view");
var import_obsidian3 = require("obsidian");
var SharedFloatingButton = class {
  constructor() {
    this.el = null;
  }
  show(top, left, onClick) {
    if (!this.el) {
      this.el = this.createEl(onClick);
    }
    this.el.style.top = `${top}px`;
    this.el.style.left = `${left}px`;
    this.el.classList.add("visible");
  }
  hide() {
    if (this.el) {
      this.el.classList.remove("visible");
    }
  }
  remove() {
    if (this.el) {
      this.el.remove();
      this.el = null;
    }
  }
  createEl(onClick) {
    const btn = document.createElement("button");
    btn.className = "notepipe-floating-btn";
    btn.title = t("floating.tooltip");
    btn.setAttribute("aria-label", t("floating.tooltip"));
    btn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
        </svg>`;
    btn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      onClick();
      this.hide();
    });
    btn.addEventListener("mousedown", (e) => {
      e.preventDefault();
      e.stopPropagation();
    });
    document.body.appendChild(btn);
    return btn;
  }
};
function selectionEndCoords(view) {
  const pos = view.state.selection.main.to;
  const coords = view.coordsAtPos(pos);
  if (!coords) return null;
  return {
    top: coords.top - 32,
    left: coords.right + 4
  };
}
var EditorSelectionWatcher = class {
  constructor(view, button, onClick) {
    this.button = button;
    this.onClick = onClick;
    this.updateButton(view);
  }
  update(update) {
    if (update.selectionSet || update.docChanged) {
      this.updateButton(update.view);
    }
  }
  updateButton(view) {
    const sel = view.state.selection.main;
    if (sel.empty) {
      this.button.hide();
      return;
    }
    const coords = selectionEndCoords(view);
    if (!coords) {
      this.button.hide();
      return;
    }
    this.button.show(coords.top, coords.left, this.onClick);
  }
  destroy() {
    this.button.hide();
  }
};
function createFloatingButtonExtension(button, onClick) {
  return import_view.ViewPlugin.define(
    (view) => new EditorSelectionWatcher(view, button, onClick)
  );
}
var FloatingButtonManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.button = new SharedFloatingButton();
    this.boundMouseUpHandler = this.onMouseUp.bind(this);
    this.boundScrollHandler = () => this.button.hide();
  }
  /** 获取共享按钮实例（供 CM6 extension 使用） */
  getSharedButton() {
    return this.button;
  }
  activate() {
    document.addEventListener("mouseup", this.boundMouseUpHandler);
    document.addEventListener("scroll", this.boundScrollHandler, { capture: true });
  }
  deactivate() {
    document.removeEventListener("mouseup", this.boundMouseUpHandler);
    document.removeEventListener("scroll", this.boundScrollHandler, { capture: true });
    this.button.hide();
    this.button.remove();
  }
  // -------------------------------------------------------------------
  // 阅读模式事件处理
  // -------------------------------------------------------------------
  onMouseUp(_event) {
    requestAnimationFrame(() => this.handleSelection());
  }
  handleSelection() {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed || !selection.toString().trim()) {
      this.button.hide();
      return;
    }
    const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!activeView || activeView.getMode() !== "preview") {
      this.button.hide();
      return;
    }
    if (selection.rangeCount === 0) {
      this.button.hide();
      return;
    }
    const range = selection.getRangeAt(0);
    const viewContainer = activeView.previewMode?.containerEl ?? activeView.containerEl;
    if (!viewContainer.contains(range.commonAncestorContainer)) {
      this.button.hide();
      return;
    }
    const rect = range.getBoundingClientRect();
    const top = rect.top - 32;
    const left = rect.right + 4;
    this.button.show(top, left, () => {
      this.plugin.copyGlobalContext();
    });
  }
  // -------------------------------------------------------------------
  // 强制刷新
  // -------------------------------------------------------------------
  forceUpdate() {
    this.button.hide();
  }
};

// src/copy-interceptor.ts
var import_view2 = require("@codemirror/view");
var import_obsidian4 = require("obsidian");
function debounce(fn, delay) {
  let timer = null;
  return () => {
    if (timer !== null) clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      fn();
    }, delay);
  };
}
var CopyInterceptorPlugin = class {
  constructor(view, plugin) {
    this.plugin = plugin;
    this.debouncedCopy = debounce(() => {
      const selection = view.state.selection.main;
      if (selection.empty) return;
      const selectedText = view.state.sliceDoc(
        selection.from,
        selection.to
      );
      if (selectedText.trim().length === 0) return;
      this.plugin.copyGlobalContext();
    }, 300);
  }
  update(update) {
    if (update.selectionSet) {
      this.debouncedCopy();
    }
  }
  destroy() {
  }
};
function copyInterceptorExtension(plugin) {
  return import_view2.ViewPlugin.define(
    (view) => new CopyInterceptorPlugin(view, plugin)
  );
}
var globalSelectionHandler = null;
function registerGlobalCopyInterceptor(plugin) {
  if (import_obsidian4.Platform.isMobile) return;
  const debouncedCopy = debounce(() => {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed) return;
    const text = selection.toString();
    if (text.trim().length === 0) return;
    const activeView = plugin.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!activeView || activeView.getMode() !== "preview") {
      return;
    }
    plugin.copyGlobalContext();
  }, 300);
  globalSelectionHandler = () => {
    requestAnimationFrame(() => debouncedCopy());
  };
  document.addEventListener(
    "selectionchange",
    globalSelectionHandler
  );
}
function unregisterGlobalCopyInterceptor() {
  if (globalSelectionHandler) {
    document.removeEventListener(
      "selectionchange",
      globalSelectionHandler
    );
    globalSelectionHandler = null;
  }
}

// src/main.ts
var NotePipePlugin = class extends import_obsidian5.Plugin {
  // -----------------------------------------------------------------------
  // 生命周期
  // -----------------------------------------------------------------------
  async onload() {
    await this.loadSettings();
    loadLocale();
    this.addSettingTab(new NotePipeSettingTab(this.app, this));
    this.addCommand({
      id: "copy-with-context",
      name: t("command.copyWithContext"),
      editorCallback: (editor, view) => this.copyWithContext(editor, view),
      hotkeys: this.settings.enableHotkey ? [{ modifiers: ["Mod", "Shift"], key: "c" }] : void 0
    });
    this.addCommand({
      id: "copy-with-context-global",
      name: t("command.copyWithContextGlobal"),
      callback: () => this.copyGlobalContext()
    });
    if (this.settings.showFloatingButton) {
      this.floatingButton = new FloatingButtonManager(this);
      this.registerEditorExtension(
        createFloatingButtonExtension(
          this.floatingButton.getSharedButton(),
          () => this.copyGlobalContext()
        )
      );
      this.floatingButton.activate();
    }
    if (this.settings.enableAlwaysCopy) {
      this.registerEditorExtension(copyInterceptorExtension(this));
      registerGlobalCopyInterceptor(this);
    }
  }
  async onunload() {
    if (this.floatingButton) {
      this.floatingButton.deactivate();
    }
    unregisterGlobalCopyInterceptor();
  }
  // -----------------------------------------------------------------------
  // 设置持久化
  // -----------------------------------------------------------------------
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // -----------------------------------------------------------------------
  // 核心复制逻辑
  // -----------------------------------------------------------------------
  /**
   * 编辑模式复制（命令面板 / 快捷键触发）。
   */
  async copyWithContext(editor, view) {
    const context = await resolveContext(this.app, editor, view);
    if (!context) {
      new import_obsidian5.Notice(t("notice.noContext"));
      return;
    }
    if (context.source === "file-explorer" && context.files) {
      await this.copyFileList(context.files);
      return;
    }
    await this.copyResolvedContext(context);
  }
  /**
   * 全局复制（阅读模式 / 文件列表 / 编辑模式浮层按钮点击等场景）。
   */
  async copyGlobalContext() {
    const fileListContext = resolveFileExplorerContext();
    if (fileListContext) {
      await this.copyFileList(fileListContext.files);
      return;
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (activeView && activeView.getMode() === "source" && activeView.editor) {
      const selection = activeView.editor.getSelection();
      if (selection.trim().length > 0) {
        const context2 = await resolveContext(
          this.app,
          activeView.editor,
          activeView
        );
        if (context2) {
          await this.copyResolvedContext(context2);
          return;
        }
      }
    }
    const context = await resolveContext(this.app);
    if (!context) {
      new import_obsidian5.Notice(t("notice.noContext"));
      return;
    }
    await this.copyResolvedContext(context);
  }
  /**
   * 将 ResolvedContext 渲染并写入剪贴板。
   */
  async copyResolvedContext(context) {
    const isMultiLine = context.startLine !== null && context.endLine !== null && context.endLine > context.startLine;
    const template = isMultiLine ? this.settings.multiLineTemplate : this.settings.singleLineTemplate;
    const displayPath = formatPath(
      context.path,
      this.settings.pathStyle,
      this.app
    );
    const safeSelection = context.selection ? truncateSelection(context.selection, 100 * 1024, t("notice.truncated")) : context.selection;
    const templateCtx = buildTemplateContext(
      displayPath,
      safeSelection,
      context.startLine,
      context.endLine
    );
    const formatted = renderTemplate(template, templateCtx);
    try {
      await navigator.clipboard.writeText(formatted);
      new import_obsidian5.Notice(t("notice.copied"));
    } catch {
      new import_obsidian5.Notice(t("notice.clipboardUnavailable"));
    }
  }
  /**
   * 文件列表场景：复制多文件路径。
   */
  async copyFileList(files) {
    const lines = files.map(
      (f) => formatPath(f, this.settings.pathStyle, this.app)
    );
    const text = lines.join("\n") + "\n";
    try {
      await navigator.clipboard.writeText(text);
      new import_obsidian5.Notice(t("notice.copied"));
    } catch {
      new import_obsidian5.Notice(t("notice.clipboardUnavailable"));
    }
  }
};
